// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtkWF2vukgufQvnYT49Ts70p63fps5bwA',
    appId: '1:1047279372959:web:40454bb2caf9332f8330aa',
    messagingSenderId: '1047279372959',
    projectId: 'fithify',
    authDomain: 'fithify.firebaseapp.com',
    storageBucket: 'fithify.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGkFC2DThZBdqBdtcBuZWrLrDpSX8NP8',
    appId: '1:1047279372959:android:7e2221b3acb0b4b88330aa',
    messagingSenderId: '1047279372959',
    projectId: 'fithify',
    storageBucket: 'fithify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhCjA94ZgIRMQpY-D4mpKH-W_7iKa9B9k',
    appId: '1:1047279372959:ios:b74e8b7f2c9ba5938330aa',
    messagingSenderId: '1047279372959',
    projectId: 'fithify',
    storageBucket: 'fithify.firebasestorage.app',
    iosBundleId: 'com.example.fitHify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhCjA94ZgIRMQpY-D4mpKH-W_7iKa9B9k',
    appId: '1:1047279372959:ios:b74e8b7f2c9ba5938330aa',
    messagingSenderId: '1047279372959',
    projectId: 'fithify',
    storageBucket: 'fithify.firebasestorage.app',
    iosBundleId: 'com.example.fitHify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtkWF2vukgufQvnYT49Ts70p63fps5bwA',
    appId: '1:1047279372959:web:369c4aeed440f2168330aa',
    messagingSenderId: '1047279372959',
    projectId: 'fithify',
    authDomain: 'fithify.firebaseapp.com',
    storageBucket: 'fithify.firebasestorage.app',
  );
}
